version: "3"

networks:
  webguinet:
  
volumes:
  db:
  .:

services:

  database:
    image: mysql:5.7
    restart: always
    networks:
     - webguinet
    ports:
      - '9082:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pass4root
      MYSQL_DATABASE: praktyki
      MYSQL_USER: praktyki
      MYSQL_PASSWORD: pass4praktyki
    # Where our data will be persisted
    volumes:
      - ./compose/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "5"
        
        
  web:
    depends_on:
      - database
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - webguinet
    ports:
      - 127.0.0.1:9081:9081
    expose:
      - 9081
    volumes:
      - .:/code  
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "5"
