# Generated by Django 3.1.7 on 2021-04-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SFibersStackCalibratorPar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('version', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'SFibersStackCalibratorPar',
            },
        ),
        migrations.CreateModel(
            name='SFibersStackDDLookupTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('version', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'SFibersStackDDLookupTable',
            },
        ),
        migrations.CreateModel(
            name='SFibersStackDDUnpackerPar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('version', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'SFibersStackDDUnpackerPar',
            },
        ),
        migrations.CreateModel(
            name='SFibersStackDigitizerPar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('version', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'SFibersStackDigitizerPar',
            },
        ),
        migrations.CreateModel(
            name='SFibersStackGeomPar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('version', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'SFibersStackGeomPar',
            },
        ),
        migrations.CreateModel(
            name='SFibersStackHitFinderFiberPar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('version', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'SFibersStackHitFinderFiberPar',
            },
        ),
        migrations.CreateModel(
            name='SFibersStackHitFinderPar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('version', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'SFibersStackHitFinderPar',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('run_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'files',
                'unique_together': {('run_id', 'start_time', 'stop_time')},
            },
        ),
    ]
