# Generated by Django 3.1.7 on 2021-04-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'files', 'verbose_name_plural': 'files'},
        ),
        migrations.AlterModelOptions(
            name='sfibersstackcalibratorpar',
            options={'verbose_name': 'SFibersStackCalibratorPar', 'verbose_name_plural': 'SFibersStackCalibratorPar'},
        ),
        migrations.AlterModelOptions(
            name='sfibersstackddlookuptable',
            options={'verbose_name': 'SFibersStackDDLookupTable', 'verbose_name_plural': 'SFibersStackDDLookupTable'},
        ),
        migrations.AlterModelOptions(
            name='sfibersstackddunpackerpar',
            options={'verbose_name': 'SFibersStackDDUnpackerPar', 'verbose_name_plural': 'SFibersStackDDUnpackerPar'},
        ),
        migrations.AlterModelOptions(
            name='sfibersstackdigitizerpar',
            options={'verbose_name': 'SFibersStackDigitizerPar', 'verbose_name_plural': 'SFibersStackDigitizerPar'},
        ),
        migrations.AlterModelOptions(
            name='sfibersstackgeompar',
            options={'verbose_name': 'SFibersStackGeomPar', 'verbose_name_plural': 'SFibersStackGeomPar'},
        ),
        migrations.AlterModelOptions(
            name='sfibersstackhitfinderfiberpar',
            options={'verbose_name': 'SFibersStackHitFinderFiberPar', 'verbose_name_plural': 'SFibersStackHitFinderFiberPar'},
        ),
        migrations.AlterModelOptions(
            name='sfibersstackhitfinderpar',
            options={'verbose_name': 'SFibersStackHitFinderPar', 'verbose_name_plural': 'SFibersStackHitFinderPar'},
        ),
    ]
