# Generated by Django 3.1.7 on 2021-04-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210422_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'verbose_name': 'Release', 'verbose_name_plural': 'Release'},
        ),
        migrations.AlterModelTable(
            name='release',
            table='Release',
        ),
    ]
