# Generated by Django 3.1.7 on 2021-04-16 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfibersstackcalibratorpar',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sfibersstackcalibratorpar_versions', to='core.release'),
        ),
        migrations.AddField(
            model_name='sfibersstackddlookuptable',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sfibersstackddlookuptable_versions', to='core.release'),
        ),
        migrations.AddField(
            model_name='sfibersstackddunpackerpar',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sfibersstackddunpackerpar_versions', to='core.release'),
        ),
        migrations.AddField(
            model_name='sfibersstackdigitizerpar',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sfibersstackdigitizerpar_versions', to='core.release'),
        ),
        migrations.AddField(
            model_name='sfibersstackgeompar',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sfibersstackgeompar_versions', to='core.release'),
        ),
        migrations.AddField(
            model_name='sfibersstackhitfinderfiberpar',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sfibersstackhitfinderfiberpar_versions', to='core.release'),
        ),
        migrations.AddField(
            model_name='sfibersstackhitfinderpar',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sfibersstackhitfinderpar_versions', to='core.release'),
        ),
    ]
