-- MySQL Script generated by MySQL Workbench
-- pon, 15 mar 2021, 22:14:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`configuration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`configuration` (
  `id` INT(10) UNSIGNED NOT NULL,
  `parameters` TEXT NOT NULL,
  `valid_from` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `valid_to` DATETIME NOT NULL,
  `version` INT(11) NOT NULL DEFAULT 1,
  `remarks` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'An abstract base table which reflects the structure of a single configuration.';


-- -----------------------------------------------------
-- Table `mydb`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`files` (
  `id` INT(11) NOT NULL,
  `file_name` VARCHAR(255) NULL DEFAULT NULL,
  `start_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `stop_time` DATETIME NOT NULL,
  `remarks` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'A table for saving information about output files';


-- -----------------------------------------------------
-- Table `mydb`.`SFibersStackCalibratorPar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SFibersStackCalibratorPar` (
  `id` INT(10) UNSIGNED NOT NULL,
  `parameters` TEXT NOT NULL,
  `valid_from` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `valid_to` DATETIME NOT NULL,
  `version` INT(11) NOT NULL DEFAULT 1,
  `remarks` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'An abstract base table which reflects the structure of a single configuration.';


-- -----------------------------------------------------
-- Table `mydb`.`SFibersStackDDLookupTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SFibersStackDDLookupTable` (
  `id` INT(10) UNSIGNED NOT NULL,
  `parameters` TEXT NOT NULL,
  `valid_from` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `valid_to` DATETIME NOT NULL,
  `version` INT(11) NOT NULL DEFAULT 1,
  `remarks` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'An abstract base table which reflects the structure of a single configuration.';


-- -----------------------------------------------------
-- Table `mydb`.`SFibersStackDDUnpackerPar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SFibersStackDDUnpackerPar` (
  `id` INT(10) UNSIGNED NOT NULL,
  `parameters` TEXT NOT NULL,
  `valid_from` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `valid_to` DATETIME NOT NULL,
  `version` INT(11) NOT NULL DEFAULT 1,
  `remarks` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'An abstract base table which reflects the structure of a single configuration.';


-- -----------------------------------------------------
-- Table `mydb`.`SFibersStackDigitizerPar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SFibersStackDigitizerPar` (
  `id` INT(10) UNSIGNED NOT NULL,
  `parameters` TEXT NOT NULL,
  `valid_from` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `valid_to` DATETIME NOT NULL,
  `version` INT(11) NOT NULL DEFAULT 1,
  `remarks` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'An abstract base table which reflects the structure of a single configuration.';


-- -----------------------------------------------------
-- Table `mydb`.`SFibersStackGeomPar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SFibersStackGeomPar` (
  `id` INT(10) UNSIGNED NOT NULL,
  `parameters` TEXT NOT NULL,
  `valid_from` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `valid_to` DATETIME NOT NULL,
  `version` INT(11) NOT NULL DEFAULT 1,
  `remarks` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'An abstract base table which reflects the structure of a single configuration.';


-- -----------------------------------------------------
-- Table `mydb`.`SFibersStackHitFinderFiberPar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SFibersStackHitFinderFiberPar` (
  `id` INT(10) UNSIGNED NOT NULL,
  `parameters` TEXT NOT NULL,
  `valid_from` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `valid_to` DATETIME NOT NULL,
  `version` INT(11) NOT NULL DEFAULT 1,
  `remarks` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'An abstract base table which reflects the structure of a single configuration.';


-- -----------------------------------------------------
-- Table `mydb`.`SFibersStackHitFinderPar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SFibersStackHitFinderPar` (
  `id` INT(10) UNSIGNED NOT NULL,
  `parameters` TEXT NOT NULL,
  `valid_from` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `valid_to` DATETIME NOT NULL,
  `version` INT(11) NOT NULL DEFAULT 1,
  `remarks` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'An abstract base table which reflects the structure of a single configuration.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
